### ISSUE TITLE
Running Multiple Build is creating nested hierarchy in deployment folder

### ISSUE THREAD

**Issue by gopalanand333** [SAP/cloud-sdk-cli#103]
**Describe The Bug**
Whenever I am trying to run `npm run deploy` for 2nd time onwards on a project, it's creating a nested hierarchy of deployment folder inside the deployment folder. This is breaking the path and cf deployment is not able to find main.ts
I have 3 projects. 2 of them are working fine but this behavior is occurring for only one project. Please find the folder structure generated in the attached image.
Every time when I have to deploy the application, I have to delete the previous build.

1st build-
![first build](https://user-images.githubusercontent.com/32189444/89613919-f7ae8c80-d8a0-11ea-9491-5c9e5d9245de.PNG)
2nd build- You can see there's a deployment under the deployment folder.
![2nd build](https://user-images.githubusercontent.com/32189444/89613913-f4b39c00-d8a0-11ea-9036-03800466d3bd.PNG)

**To Reproduce**

1. run `npm run deploy` 2 times.

**Expected Behavior**

It should deploy the application without error, we should not delete the previous build manually.

**Used Versions:**
- @sap-cloud-sdk/cli/0.1.10 win32-x64 node-v12.16.1
- npm: '6.13.4'

**Folder structure of the application where the build is failing**

![logistics service](https://user-images.githubusercontent.com/32189444/89614519-3c86f300-d8a2-11ea-94dc-f30d5ee320d2.PNG)

**Comment by CharlesDuboisSAP** [comment]
Hello @gopalanand333,
I can't reproduce the bug so I have a few questions:
- What is your deployment script? (it's located in package.json under "scripts")
- Is your deployment folder inside the project folder?

**Comment by gopalanand333** [comment]
Hi @CharlesDuboisSAP,

- Deployment script:   "deploy": "npm run build && sap-cloud-sdk package && cf push". I am using npm run deploy 
- Yup, my deployment folder is under the project folder. While building I can see the dist folder is deleted and generated again but the deployment folder is having different behavior. 
![image](https://user-images.githubusercontent.com/32189444/89755769-2f664000-dafe-11ea-988c-11ffeeb9e40a.png)

One point to note is that it's working fine for 2/3, just one is failing.

**Comment by FrankEssenberger** [comment]
Good morning,

could you perhaps share the failing project so that we have an example to reproduce the error. 

Best
Frank

**Comment by CharlesDuboisSAP** [comment]
@gopalanand333 
You added `"allowJs": true` in your tsconfig.json file which looks for all js files, even the ones in the deployment folder and puts them again in the dist folder.


Here are the solutions:
- Delete this option from the tsconfig.json file. You only have ts files in your source folder, you don't need to look for js files.
- Add the deployment folder to the exclude list in tsconfig.build.json
- Add an include list the same way as the exclude list that only looks in the src folder

In the long run we will probably exclude the deployment folder or only include the src folder in order to allow the user to add `"allowJs": true` without it making nested folders.

**Comment by gopalanand333** [comment]
@CharlesDuboisSAP 
Thanks for providing these solutions. 
Deleting the `"allowJs": true` worked. 

People might use js files in the future, it will be good to have the deployment folder in exclude list by default in the future.

Best regards,
Gopal
