### ISSUE TITLE
add-approuter produces files with errors (+UX issues)

### ISSUE THREAD

**Issue by mr-flannery** [SAP/cloud-sdk-cli#150]
**Describe The Bug**

Running `add-approuter` produces the following problems:

1. It generates an `.npmrc` that points to registry that is not available externally.
2. The `TENANT_HOST_PATTERN` variable in the generated `manifest.yml` has the wrong YAML data type. It's generated like this:
```yaml
TENANT_HOST_PATTERN: >-
  "my-sdk-app-(.*).cfapps.sap.hana.ondemand.com"
```
However, when parsing this, the quotes (`"`) are actually interpreted as literals, i.e. the JSON equivalent is `"\"my-sdk-app-(.*).cfapps.sap.hana.ondemand.com\"". Both of the following options would work:
```yaml
TENANT_HOST_PATTERN: >-
  my-sdk-app-(.*).cfapps.sap.hana.ondemand.com
# or
TENANT_HOST_PATTERN: "my-sdk-app-(.*).cfapps.sap.hana.ondemand.com"
```
3. While we're at it, if you use `my-sdk-app-(.*).cfapps.(.*).hana.ondemand.com`, you can even abstract from the landscape (since `sap` is canary anyway).
4. Currently, the approuter's `destination` variable is generated like this: `[{ "name": my-sdk-app", "url": "my-sdk-app.cfapps.sap.hana.ondemand.com", "forwardAuthToken": true}]`. The approuter will fail on startup, though, because it expects a protocol at the beginning of the url (the log says it expects an "absolute URL", but adding `https://` in front of it does fix it).
5. From an UX perspective, there are some problems with the generated manifest. For example, it generates a route like this:
```
routes:
      - route: >-
          my-sdk-app-apps.cfapps.sap.hana.ondemand.com
```
I wasted about an hour today because I forgot that this url does not yet contain the tenant (which wasn't really obvious at first, but it explains why my app did not redirect me to the custom IdP I registered in my subaccount, i.e. using the tenant-aware XSUAA url `tenant.authentication.sap.com` but just `authentication.sap.com`). Now this is obviously my own fault, but I think there are ways to prevent such errors.
Option 1: ask for the tenant name when generating the approuter files.
Option 2: put a comment in the manifest.yml, explicitly stating that the correct tenant aware route needs to be configured or added via the `cf map-route` command.
Btw, same goes for the landscape, this wouldn't work on a factory landscape like eu10 for example.

**To Reproduce**

Generate a new project with `init` and then run `add-approuter`.

**Expected Behavior**

Generated files should work out of the box where possible, or the files (or the command's output) should contain clear and explicit hints which things I need to adapt in order to make it work.

**Used Versions:**

 - `sap-cloud-sdk -v`: `@sap-cloud-sdk/cli/0.1.12 darwin-x64 node-v10.16.3`

**Comment by jjtang1985** [comment]
This repository is deprecated.
As replacement, we provide extensive setup guides for your projects: https://github.com/SAP-samples/cloud-sdk-js.
