### ISSUE TITLE
Installation documentation 

### ISSUE THREAD

**Issue by bsrdjan** [SAP/cloud-sdk-cli#495]
In the installation documentation, it is possible to click on "Copy", to copy the installation command to clipboard:

`npm install -g @sap-cloud-sdk/cli@latest`

The copied command does not work because also the leading dollar sign is copied:

```shell
$ npm install -g @sap-cloud-sdk/cli@latest
zsh: command not found: $
```

The documentation shall be fixed: https://sap.github.io/cloud-sdk/docs/js/getting-started#installation

**Comment by jjtang1985** [comment]
This repository is deprecated.
As replacement, we provide extensive setup guides for your projects: https://github.com/SAP-samples/cloud-sdk-js.
