### ISSUE TITLE
Error by execution of sap-cloud-sdk init

### ISSUE THREAD

**Issue by emildinchev** [SAP/cloud-sdk-cli#513]
The execution of the command sap-cloud-sdk init hangs on step Building application scaffold. When I interrupt it, the following error is shown:
# sap-cloud-sdk init -v
The target directory (.) does not contain a `package.json.`
Should a new `nest.js` project be initialized in the target directory? (y|n): y
Building application scaffold... ⡿
Need to install the following packages:
Building application scaffold... ⡿
npm ERR! canceled

npm ERR! A complete log of this run can be found in:
Building application scaffold... !
 ›   Error: Error: Command failed with exit code 1: npx -p @nestjs/cli nest new . --skip-install --package-manager npm
 ›       at makeError (/root/.nvm/versions/node/v17.1.0/lib/node_modules/@sap-cloud-sdk/cli/node_modules/execa/lib/error.js:59:11)
 ›       at handlePromise (/root/.nvm/versions/node/v17.1.0/lib/node_modules/@sap-cloud-sdk/cli/node_modules/execa/index.js:114:26)
 ›       at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ›       at async Object.buildScaffold (/root/.nvm/versions/node/v17.1.0/lib/node_modules/@sap-cloud-sdk/cli/lib/utils/scaffold.js:45:5)
 ›       at async Init.run (/root/.nvm/versions/node/v17.1.0/lib/node_modules/@sap-cloud-sdk/cli/lib/commands/init.js:21:17)
 ›       at async Init._run (/root/.nvm/versions/node/v17.1.0/lib/node_modules/@sap-cloud-sdk/cli/node_modules/@oclif/command/lib/command.js:43:20)
 ›       at async Config.runCommand 
 ›   (/root/.nvm/versions/node/v17.1.0/lib/node_modules/@sap-cloud-sdk/cli/node_modules/@oclif/config/lib/config.js:173:24)
 ›       at async Main.run (/root/.nvm/versions/node/v17.1.0/lib/node_modules/@sap-cloud-sdk/cli/node_modules/@oclif/command/lib/main.js:27:9)
 ›       at async Main._run (/root/.nvm/versions/node/v17.1.0/lib/node_modules/@sap-cloud-sdk/cli/node_modules/@oclif/command/lib/command.js:43:20) 

I'm on WIndows 10 with WSL2 based on Ubuntu. The command was executed in WSL2 environment.

**Used Versions:**

 - node -v: [v17.1.0]
 - npm -v: [8.1.2]
 - sap-cloud-sdk -v: [@sap-cloud-sdk/cli/0.1.12 wsl-x64 node-v17.1.0]

**Comment by deekshas8** [comment]
Hi @emildinchev,

Thank you for approaching us and providing information regarding your dev environment.

I was unable to reproduce the issue in the same setup. The scaffold step took some time(~2-3 mins) but was ultimately successful.
![image](https://user-images.githubusercontent.com/88374536/144286353-24c9a79c-f67f-42cb-b1f2-cb281190c8bf.png)


Could you please try to run the command again but not interrupt the process this time? 

Please bare in mind that we are planning to deprecate the CLI from December and don't recommend using it. We'll replace its features with starter projects for different scenarios and documentation on how to use the corresponding tooling like `cf` CLI and some others to have your App deployed.

Regards.

**Comment by jjtang1985** [comment]
This repository is deprecated.
As replacement, we provide extensive setup guides for your projects: https://github.com/SAP-samples/cloud-sdk-js.
