### ISSUE TITLE
Installation of generator fails

### ISSUE THREAD

**Issue by FrankEssenberger** [SAP/cloud-sdk-cli#68]
**Describe The Bug**

If you use the generate-odata-client command in the CLI this needs the generator to run. So you are asked to install it globally if not present. 
On my machine I had it already installed but got the prompt to install it again:

```
To generate an OData client, it is necessary to install the @sap-cloud-sdk/generator.
For now, the CLI expects the generator to be installed globally.

Do you want to install the @sap-cloud-sdk/generator globally? (y|n): y
```

Then in the installation process it fails since the link is alread there:
```
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/@sap-cloud-sdk/generator/dist/generator-cli.js' -> '/usr/local/bin/generate-odata-client'
npm ERR! File exists: /usr/local/bin/generate-odata-client
npm ERR! Remove the existing file and try again, or run npm
```

When I remove the link the installation runs smooth and then also the creation of the VDM works fine. 

**To Reproduce**

- Install the generator globally (@sap-cloud-sdk/generator)
- Run `sap-cloud-sdk generate-odata-client`
- You still get the prompt `it is not installed`
- When you say `yes` do it the installation fails due to the existing link.

**Expected Behavior**

Either recognise the exisiting installation properly or adjust the install so that it does not fail.

**Used Versions:**

 - `node -v`: v13.13.0
 - `npm -v`:  6.14.4
 - `sap-cloud-sdk -v`: @sap-cloud-sdk/cli/0.1.8 darwin-x64 node-v13.13.0

**Additional Context**

I know that the issue is perhaps hard to reproduce why the CLI thought the generator is not installed.

**Comment by jjtang1985** [comment]
This repository is deprecated.
As replacement, we provide extensive setup guides for your projects: https://github.com/SAP-samples/cloud-sdk-js.
