### ISSUE TITLE
Error While generating project with cloud-sdk-cli

### ISSUE THREAD

**Issue by gopalanand333** [SAP/cloud-sdk-cli#71]
I'm trying to initialize a project with sap-cloud-sdk init
It's giving the following error:

sap-cloud-sdk init test
The target directory (test) does not contain a package.json.
Should a new nest.js project be initialized in the target directory? (y|n): y
Building application scaffold... !
» Error: Command failed with exit code 1: npx -p @nestjs/cli nest new . --skip-install --package-manager npm

To Reproduce
sap-cloud-sdk init test

Expected behavior
It should create a project template

Used Versions:
@sap-cloud-sdk/cli/0.1.9 win32-x64 node-v12.16.1

I have attached logs of output after running the command
[log.txt](https://github.com/SAP/cloud-sdk-cli/files/4823689/log.txt)
: npx -p @nestjs/cli nest new . --skip-install --package-manager npm

**Comment by marikaner** [comment]
Hey @gopalanand333,

From the logs you sent it seems that there is either an issue with nestjs or your local npm cache. I tried the command on a windows machine and it worked, so I am assuming this might rather be a problem with your local npm cache. Can you please run `npm cache clean --force` and try again?

**Comment by gopalanand333** [comment]
Hi @marikaner ,
It worked.
Thanks a lot for your instant Support.

Best regards,
Gopal
